.TH biblical-texts 1

.SH NAME
biblical-texts \- print biblical texts in your terminal

.SH SYNOPSIS
.PP
biblical-texts [options] <arguments>

.SH DESCRIPTION
.PP 
biblical-texts print biblical texts in your terminal

.SH OPTIONS
.HP
\fB\-\-help\fR, \fB\-h\fR
.IP
Show this message and exit
.HP
\fB\-\-version\fR, \fB\-v\fR
.IP
Show the version and exit
.HP
\fB\-\-trace=\fR<file>, \fB\-t\fR <file>
.IP
<file> is the path of the debug file
.HP
\fB\-\-debug\-level=\fR<number>, \fB\-d\fR <number>
.IP
<number> is the level of debug level
.HP
\fB\-\-colored\-log\fR, \fB\-c\fR
.IP
Set a colored log
.HP
\fB\-\-conf\-filename=\fR<file>, \fB\-C\fR <file>
.IP
<file> is the path of the .conf file of software

.SH BUGS
.PP
For reporting bugs, send a email to <gustavo.bacagine@protonmail.com>

.SH AUTHOR
.PP
Gustavo Bacagine <gustavo.bacagine@protonmail.com>

